version: '3'

services:
  redis-cache:
    image: redis:7-alpine
    volumes:
      - redis:/data

  exchange-api:
    image: kotasha/go-exchange-api:latest
    environment:
      EXCHANGE_API_REDIS: redis://redis-cache:6379/0
    ports:
      - 8080:8080/tcp
    depends_on:
      - redis-cache

volumes:
  redis:
